#!/bin/bash
docker-compose up -d
sleep 10
pnpm install
sleep 30
cd apps/backend
npm run seed:run
sleep 20
cd ..
cd ..
pnpm run dev --filter backend &
sleep 10
pnpm run dev --filter demo &
echo "Ready to Test"
